benchmark: core/native/randomized_benchmarking

benchmark_params:
  num_qubits: 2
  lengths: [1, 2, 4, 8, 16]
  num_sequences: 5

adapter: qmio_qiskit
backend: QMIO

calibration_file: /opt/cesga/qmio/hpc/calibrations/2026_03_13__12_00_01.json

shots: 512

output_dir: "./results_qmio"

# Controls what is generated
report:
  analysis:
    enabled: true
    visualization:
      enabled: true
      show: true

# Controls how results are persisted
storage:
  enabled: true
  type: "file"  # "file" or "sqlite"
  file:
    format: "json"
  sqlite:
    db_path: "./mqssbench.db"
  
profiling:
  enabled: false
