benchmark: core/native/quantum_volume

benchmark_params:
  num_qubits: 2
  depth: 2
  trials: 2

adapter: qmio_qiskit
backend: QMIO

calibration_file: /opt/cesga/qmio/hpc/calibrations/2026_03_13__12_00_01.json

shots: 200

output_dir: "./results_qmio"

# Controls how results are persisted
storage:
  enabled: true
  type: "file" 
  file:
    format: "json"

profiling:
  enabled: false